apiVersion: v1
kind: ConfigMap
metadata:
  name: wait-gcs-ready 
data:
  wait-gcs-ready.sh: |
    #!/bin/bash

    SECONDS=0
    while true; do
            if (( SECONDS <= 120 )); then
                    if ray health-check --address $1:$2 > /dev/null 2>&1; then
                            echo "GCS is ready."
                            break
                    fi
                    echo "$SECONDS seconds elapsed: Waiting for GCS to be ready."
            else
                    if ray health-check --address $3:$4; then
                            echo "GCS is ready. Any error messages above can be safely ignored."
                            break
                    fi
                    echo "$SECONDS seconds elapsed: Still waiting for GCS to be ready. For troubleshooting, refer to the FAQ at https://github.com/ray-project/kuberay/blob/master/docs/guidance/FAQ.md."
            fi
            sleep 5               
    done
