# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stable_diffusion.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16stable_diffusion.proto\"(\n\x16StableDiffusionRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"+\n\x17StableDiffusionResponse\x12\x10\n\x08\x63ontents\x18\x01 \x01(\x0c\x32W\n\x16StableDiffusionService\x12=\n\x08Generate\x12\x17.StableDiffusionRequest\x1a\x18.StableDiffusionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stable_diffusion_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STABLEDIFFUSIONREQUEST']._serialized_start=26
  _globals['_STABLEDIFFUSIONREQUEST']._serialized_end=66
  _globals['_STABLEDIFFUSIONRESPONSE']._serialized_start=68
  _globals['_STABLEDIFFUSIONRESPONSE']._serialized_end=111
  _globals['_STABLEDIFFUSIONSERVICE']._serialized_start=113
  _globals['_STABLEDIFFUSIONSERVICE']._serialized_end=200
# @@protoc_insertion_point(module_scope)
